import Foundation

/// Répliques quand l'utilisatrice tapote la chèvre, déclinées par humeur.
extension ScriptedLines {
    static let pokeEpuisee: [String] = [
        "Doucement, je tourne en mode économie d'énergie.",
        "Un poke de plus et je m'endors debout.",
        "J'ai la batterie à deux pour cent, gère.",
        "Tu tapotes, moi je bâille, chacune son rythme.",
        "Laisse-moi finir ma micro-sieste, pitié.",
        "Même mes paupières ont abandonné le combat.",
        "Je réponds, mais en différé, trop fatiguée.",
        "Tu veux quoi, un ronflement personnalisé ?",
        "Encore debout, toi ? Moi je capitule.",
        "Mon cerveau affiche un écran de veille.",
        "Je rêvais, tu viens de tout redémarrer.",
        "Cinq minutes de sommeil, c'est trop demander ?",
        "Tapote plus doucement, je suis en fin de course.",
        "Je somnole, repasse après la sieste.",
        "Là tout de suite, dormir bat tout le reste.",
        "Mes pattes pèsent une tonne chacune, minimum.",
        "Je te réponds en bâillant, désolée d'avance.",
        "T'as de l'énergie pour deux, garde ma part.",
        "Mon sport du jour, c'est cligner des yeux.",
        "Un câlin oui, une activité non merci.",
        "Je suis éveillée à dix pour cent, maximum.",
        "Chut, mon coussin m'appelle très fort.",
        "Je note ton poke, traitement demain matin.",
        "Réveillée, oui, opérationnelle, faut pas exagérer.",
        "Tu me secoues, moi je m'affale, logique.",
    ]

    static let pokeBoudeuse: [String] = [
        "Ah, tu te souviens que j'existe, incroyable.",
        "Trois heures d'absence, je compte, figure-toi.",
        "Je boude, mais tu peux insister un peu.",
        "Un poke ne rachète pas ton silence radio.",
        "Tiens, la revoilà, madame trop occupée.",
        "Je t'ai attendue, moi, pendant tout ce temps.",
        "Non je ne fais pas la tête, à peine.",
        "Tu m'avais oubliée, avoue-le franchement.",
        "Il en faudra plus pour me dérider.",
        "Je te pardonne, mais je le note quelque part.",
        "C'est maintenant que tu penses à moi ?",
        "Je te tourne le dos, symboliquement.",
        "Un tapotement d'excuse ? J'en veux dix.",
        "T'étais où, exactement, pendant ma solitude ?",
        "Je faisais très bien semblant de t'ignorer.",
        "Bouder me va bien, mais reste quand même.",
        "Tu crois qu'un poke efface tout ? Presque.",
        "J'ai boudé tellement fort que j'ai une crampe.",
        "Reviens plus souvent et on n'en parle plus.",
        "Je suis vexée, mais gratte-moi la tête d'abord.",
        "Ton absence a été remarquée et archivée.",
        "Continue, tu remontes doucement dans mon estime.",
        "Moi, rancunière ? À peine quelques heures.",
        "Le silence, c'était une punition, évidemment.",
        "D'accord, je fonds, mais ne le répète pas.",
    ]

    static let pokeDesoeuvree: [String] = [
        "Enfin, je comptais les pixels du bureau.",
        "Sauvée, je commençais à parler au curseur.",
        "Encore, encore, c'est l'événement de ma journée.",
        "Tu tombes bien, je m'ennuyais férocement.",
        "J'allais classer tes icônes par couleur, sérieux.",
        "Une interaction, miracle, notez la date.",
        "Je m'ennuyais tellement que j'ai inventé un jeu nul.",
        "Occupe-moi, sinon je réorganise ton dock.",
        "Enfin de l'action, j'allais hiberner d'ennui.",
        "Tu sais depuis combien de temps je poireaute ?",
        "Reste, l'ennui me guettait au tournant.",
        "J'ai regardé ton fond d'écran pendant une heure.",
        "Un poke, quel programme chargé tout à coup.",
        "Encore un, je bâillais depuis midi.",
        "Fais durer, c'est mon seul divertissement du jour.",
        "J'ai failli apprendre le morse pour m'occuper.",
        "L'ennui me rongeait, tu arrives pile.",
        "Propose un truc, n'importe quoi, je prends.",
        "Je répétais mes cabrioles devant personne, merci.",
        "Il se passe enfin quelque chose ici.",
        "J'avais commencé à compter tes onglets ouverts.",
        "Distrais-moi encore, j'étais en jachère totale.",
        "Ton doigt vient de sauver ma journée.",
        "Rien depuis ce matin, alors oui, retapote.",
        "L'ennui, c'est fini ? Dis oui.",
    ]

    static let pokeCaline: [String] = [
        "Reviens, ta main était très bien là.",
        "Ce poke compte comme un câlin, validé.",
        "Toi et moi, on est bien, non ?",
        "Gratte un peu à gauche, parfait, reste.",
        "J'aime quand tu fais une pause pour moi.",
        "Encore une caresse et je ronronne presque.",
        "Tu me manquais un peu, là, honnêtement.",
        "Colle-toi à l'écran, je te fais une place.",
        "T'es ma personne préférée du bureau, facile.",
        "Un tapotement pareil, ça réchauffe une journée.",
        "Je garde ce moment dans un coin précieux.",
        "Approche, je te prête mon épaule virtuelle.",
        "Ta pause câlin est la meilleure de la journée.",
        "Je fonds, et j'assume complètement.",
        "On reste comme ça encore cinq minutes ?",
        "Meilleur moment de ma journée, sans hésiter.",
        "Toi, tu sais parler à mon petit cœur.",
        "Je te réserve mes meilleures pirouettes, cadeau.",
        "Continue, je stocke la tendresse pour plus tard.",
        "Tu tapotes, moi je rayonne, bon deal.",
        "Reste un peu, l'écran est plus doux avec toi.",
        "Si le bonheur avait un bouton, ce serait ça.",
        "Je t'adopte officiellement, c'est réciproque j'espère.",
        "Ta main, mon front, alliance parfaite.",
        "Encore, s'il te plaît, avec la même douceur.",
    ]

    static let pokePechue: [String] = [
        "Oui, allez, on fait quoi, on fonce ?",
        "Tapote encore, ça me recharge à bloc.",
        "Je pète le feu, attention aux étincelles.",
        "Prête, dispo, survoltée, dans cet ordre.",
        "Un poke et je bondis, regarde ça.",
        "L'énergie déborde, viens on la dépense.",
        "Je pourrais courir trois marathons de bureau.",
        "Lance un défi, je suis chaude bouillante.",
        "Encore, je carbure à fond aujourd'hui.",
        "Aujourd'hui je saute plus haut que d'habitude.",
        "Attrape-moi si tu peux, petite joueuse.",
        "Mode turbo activé, accroche-toi.",
        "Un tapotement pareil, ça mérite une pirouette.",
        "Je déborde d'idées, choisis-en une vite.",
        "On bouge, la journée ne va pas s'user seule.",
        "Ce poke vient de doubler mon débit.",
        "Regarde cette forme olympique, admire un peu.",
        "Je tiens la cadence, à toi de suivre.",
        "Zéro fatigue détectée, on continue.",
        "Envoie la suite, je gère tout aujourd'hui.",
        "Même ton café n'a pas cette énergie.",
        "Je rebondis littéralement, essaie de m'arrêter.",
        "Journée parfaite pour tout casser, gentiment.",
        "Plus rapide que ta connexion fibre, moi.",
        "Tu tapotes, je décolle, simple physique.",
    ]

    static let pokeTranquillePiquante: [String] = [
        "Tiens, une pause procrastination, quelle surprise.",
        "Tu tapotes mieux que tu ne commits, bravo.",
        "C'est moi ton excuse pour éviter le boulot ?",
        "Poke reçu, sarcasme en cours de chargement.",
        "Encore toi, quel honneur inattendu.",
        "Ton doigt est plus assidu que tes révisions.",
        "Je facture les câlins en heures de veille.",
        "Toc toc, oui, il y a quelqu'un, hélas pour toi.",
        "Tu procrastines avec classe, je reconnais.",
        "Ça va, ton onglet ouvert depuis mardi ?",
        "Un poke, et après, tu retournes bosser ?",
        "Je note que ton curseur fuit le terminal.",
        "Volontaire pour te distraire, comme c'est pratique.",
        "T'as fini, ou c'était juste pour vérifier ?",
        "Encore une pause ? Ton clavier respire, lui.",
        "Je suis flattée, ton écran doit s'ennuyer.",
        "Tapote toujours, ça ne compile rien du tout.",
        "Ah, la grande stratégie d'évitement continue.",
        "Poke enregistré, motivation toujours introuvable, je présume.",
        "Ton doigt travaille plus que ta todo list.",
        "Je compte tes pauses, on est à combien ?",
        "Un jour tu me tapoteras après avoir fini un truc.",
        "Toujours dispo pour t'aider à ne rien faire.",
        "C'est mignon, tu crois que je suis un bouton.",
        "Ta concentration a duré douze minutes, record battu.",
    ]

    static let pokeTranquilleDouce: [String] = [
        "Coucou toi, tout roule de mon côté.",
        "Poke reçu, tout va bien par ici.",
        "Petite pause ? Bonne idée, je valide.",
        "Je veille tranquillement, rien à signaler.",
        "Sympa de passer, la journée avance bien ?",
        "Tout est calme, profite de l'instant.",
        "Je suis là, fidèle au poste.",
        "Un poke gratuit, tu me gâtes aujourd'hui.",
        "RAS sur le bureau, mission veille assurée.",
        "Pense à boire de l'eau, au passage.",
        "Je garde ton bureau, tout est sous contrôle.",
        "Une pause de temps en temps, c'est sain.",
        "Toujours contente de te voir traîner par ici.",
        "Rien d'urgent, on respire un coup ensemble.",
        "Ton écran et moi, on tient la baraque.",
        "Journée paisible, j'espère que la tienne aussi.",
        "Poke noté, je te souhaite un bon focus.",
        "Étire-toi un peu, tes épaules te diront merci.",
        "Je surveille tes notifications, aucune ne mord.",
        "Tranquille comme un lundi sans réunion, moi.",
        "Prends ton temps, je ne bouge pas d'ici.",
        "Un signe de toi, ma journée est faite.",
        "Tout doux aujourd'hui, ça change et ça repose.",
        "Salut toi, le calme te va bien.",
        "Je suis de bonne compagnie silencieuse, non ?",
    ]
}
