import Foundation

/// Répliques calées sur le moment de la journée, piochées lors d'un clic.
extension ScriptedLines {
    static let heureNuit: [String] = [
        "Le terminal éclaire ton visage et personne d'autre ne veille.",
        "Ce commit de trois heures du matin, tu vas le relire demain.",
        "Tu tapes moins vite qu'il y a deux heures, j'ai remarqué.",
        "La nuit est calme, ton ventilo un peu moins.",
        "Personne ne relira ce code avant toi demain matin.",
        "Tes yeux clignent plus lentement que ton curseur.",
        "Le lit existe encore, il attend sans rien dire.",
        "À cette heure, chaque bug paraît plus grave qu'il ne l'est.",
        "Tu débogues, ou tu fixes l'écran en espérant un miracle.",
        "Demain tu liras ce code et tu demanderas qui a écrit ça.",
        "Le café d'il y a quatre heures ne fait plus effet.",
        "Tu es sans doute la seule lumière allumée de l'immeuble.",
        "Ce refactor peut très bien attendre le soleil.",
        "Les meilleures idées nocturnes sont souvent les pires du matin.",
        "Tu as déjà oublié pourquoi tu as ouvert ce fichier.",
        "Sauvegarde, éteins, et laisse ce bug dormir aussi.",
        "La nuit, les erreurs semblent se multiplier toutes seules.",
        "Encore cinq minutes, disais-tu il y a deux heures.",
        "Le silence dehors, le ventilo dedans, et toi au milieu.",
        "Je veille avec toi, mais je ne suis pas d'accord.",
        "Ton cerveau a fermé boutique, tes doigts n'ont pas suivi.",
        "Ce push nocturne, tu le regretteras à la relecture.",
        "Rien ne se règle vraiment à trois heures du matin.",
        "La nuit rend tout dramatique, même une virgule manquante.",
        "Va dormir, le terminal sera encore là demain, promis.",
    ]

    static let heurePetitMatin: [String] = [
        "Réveil très matinal ou nuit blanche, je n'ose pas demander.",
        "Impossible de savoir si tu commences ou si tu finis.",
        "Le ciel change de couleur et tu ne l'as pas vu.",
        "Café numéro un ou café numéro sept, dis-moi la vérité.",
        "Tout est calme, c'est le seul moment où rien ne sonne.",
        "Tes yeux disent une chose, ton enthousiasme en dit une autre.",
        "Le monde dort encore, tu as l'avantage pour une heure.",
        "Si tu as dormi, bravo, sinon on n'en parle pas.",
        "La première gorgée de café va tout décider aujourd'hui.",
        "Aucune notification à cette heure, profite de ce luxe rare.",
        "Tu as l'air lucide, mais je garde quelques doutes.",
        "Le lever du soleil se passe derrière ton écran, comme toujours.",
        "Personne ne t'écrira avant deux bonnes heures, respire un peu.",
        "Ta bouilloire vient de chauffer, la journée peut commencer.",
        "Premier commit avant le petit déjeuner, ambitieuse comme jamais.",
        "Tu ouvres le terminal avant les volets, encore une fois.",
        "Un réveil aussi tôt mérite au moins un vrai petit déjeuner.",
        "Le calme du matin dure peu, prends-en un morceau.",
        "Tu clignes des yeux très lentement, je ne dis rien.",
        "Debout aux aurores ou jamais couchée, le résultat se ressemble.",
        "Ce silence-là, tu ne le retrouveras plus avant ce soir.",
        "Ta tasse est déjà vide et il ne s'est rien passé.",
        "Commencer tôt c'est bien, tenir jusqu'au soir c'est mieux.",
        "Le ventilo n'a même pas eu le temps de démarrer.",
        "Tu es réveillée avant tes notifications, savoure ce petit pouvoir.",
    ]

    static let heureMatin: [String] = [
        "La journée est encore intacte, aucun bug ne l'a abîmée.",
        "Ton cerveau démarre comme un vieux disque dur, doucement.",
        "Premier café posé à droite du clavier, rituel respecté.",
        "Tes idées sont encore claires ce matin, profites-en vraiment.",
        "Attaque le truc difficile maintenant, pas à seize heures.",
        "Les notifications se réveillent, tu as quelques minutes d'avance.",
        "Ta liste de tâches n'a encore déçu personne aujourd'hui.",
        "Le terminal est propre, l'historique vide, tout est possible.",
        "Tu relis le code d'hier soir et tu comprends mon inquiétude.",
        "Matinée idéale pour ce chapitre de révisions que tu repousses.",
        "Ton café refroidit pendant que tu lis la doc, classique.",
        "Deux onglets ça va, quarante c'est déjà la fin.",
        "Le vrai piège du matin, c'est la boîte mail ouverte trop tôt.",
        "Tu as l'air concentrée, je vais faire semblant de me taire.",
        "Premier build de la journée, croisons ce qu'on peut croiser.",
        "La lumière du matin sur ton clavier, c'est plutôt joli.",
        "Rien n'est encore cassé, savoure ce moment fragile.",
        "Ton cerveau est frais, garde-le pour le problème compliqué.",
        "Le silence de la matinée vaut trois heures d'après-midi.",
        "Tu écris du code lisible, on voit que tu as dormi.",
        "Il reste le temps de bien faire les choses aujourd'hui.",
        "Deuxième café déjà, la matinée s'annonce intéressante.",
        "Tes révisions attendent gentiment, elles savent qu'elles gagneront.",
        "Ce ticket que tu évites depuis lundi te regarde encore.",
        "La matinée passe vite quand on lit trois docs en parallèle.",
    ]

    static let heureFaim: [String] = [
        "Ton ventre vient de faire un bruit, j'ai bien entendu.",
        "Le micro-ondes t'attend, il n'a que ça à faire.",
        "Finis ta fonction, puis va manger, dans cet ordre-là.",
        "Un sandwich devant l'écran, ça compte à moitié seulement.",
        "Toute la ville mange, et toi tu relis un log.",
        "Ce bug sera encore là après le déjeuner, promis juré.",
        "J'entends ton estomac plus fort que ton ventilo.",
        "Pause déjeuner, deux mots et une très bonne idée.",
        "Manger debout devant le frigo, on a vu pire, quand même.",
        "Tu as dit tout à l'heure que tu allais manger.",
        "Le café ne remplace pas un repas, tu le sais.",
        "Assiette chaude, écran éteint cinq minutes, essaie pour voir.",
        "Ton déjeuner refroidit pendant que tu cherches une virgule.",
        "Il y a des pâtes possibles dans ce placard, je le sens.",
        "Ce commit peut attendre, ton estomac beaucoup moins.",
        "Tu tapes plus lentement, c'est la faim, pas la fatigue.",
        "Un vrai repas maintenant t'évitera trois grignotages plus tard.",
        "Le micro-ondes fait le bruit qui annonce les bonnes choses.",
        "Va manger avant qu'une réunion avale ta pause.",
        "Une pause déjeuner sans écran, ça existe, paraît-il.",
        "Tu as ouvert le frigo trois fois sans rien décider.",
        "Le sandwich attend, il ne va pas se manger tout seul.",
        "Sauter le repas pour finir ça, on connaît la suite.",
        "Ton clavier a déjà goûté trois miettes, sois honnête.",
        "Mange un truc chaud, le débogage passe mieux après.",
    ]

    static let heureApresMidi: [String] = [
        "La digestion gagne contre ta concentration, c'était couru d'avance.",
        "Tu as relu la même ligne quatre fois, j'ai compté.",
        "Vingt minutes les yeux fermés et tu reviens comme neuve.",
        "Le creux de l'après-midi frappe toujours au même endroit.",
        "Ton curseur clignote plus vite que tes idées.",
        "Heure parfaite pour les tâches faciles, garde le dur pour demain.",
        "Un verre d'eau ferait plus d'effet qu'un troisième café.",
        "Ta tête descend doucement vers le clavier, je surveille.",
        "Rien ne s'écrit tout seul, mais on peut toujours espérer.",
        "Ce moment où le code devient flou sans raison valable.",
        "Lève-toi, marche jusqu'à la fenêtre, reviens, ça aide.",
        "La sieste n'est pas une défaite, c'est de la stratégie.",
        "Tu bâilles en silence, mais ton écran te trahit.",
        "Le ventilo ronronne et ça ne t'aide pas à rester réveillée.",
        "Tes commits de l'après-midi ont un style bien reconnaissable.",
        "Cette réunion aurait vraiment pu être un message écrit.",
        "Fais du tri dans tes onglets, ton cerveau dira merci.",
        "Le plus dur, c'est l'heure qui suit le repas.",
        "Tu as ouvert la doc, puis tu as pensé à autre chose.",
        "Tes yeux sont ouverts, ton attention est partie sans prévenir.",
        "Étire tes épaules, elles sont montées jusqu'aux oreilles.",
        "Deux tâches simples maintenant valent mieux qu'une grande ambition.",
        "Le soleil tape sur l'écran et personne ne baisse le store.",
        "Tu relances le build en espérant que ça change quelque chose.",
        "Un thé maintenant et tu tiendras jusqu'au soir tranquillement.",
    ]

    static let heureGouter: [String] = [
        "Ce petit creux de fin d'après-midi ne ment jamais.",
        "Il reste sûrement quelque chose de sucré dans ce placard.",
        "Dernière ligne droite, ton cerveau réclame du carburant.",
        "Un carré de chocolat et le ticket paraîtra moins hostile.",
        "Ce café de fin d'après-midi, celui qu'on regrette parfois.",
        "Tu regardes l'horloge plus souvent que ton terminal.",
        "Encore un petit effort et tu pourras fermer tout ça.",
        "Un thé chaud maintenant, ça change toute la fin de journée.",
        "Ton attention baisse, ta faim monte, joli duo.",
        "Ne commence pas un gros refactor si près de la fin.",
        "Les biscuits du placard t'appellent depuis un bon moment.",
        "Finis le petit truc, laisse le gros pour demain matin.",
        "C'est le moment où les réunions deviennent vraiment insupportables.",
        "Ton estomac réclame quelque chose entre deux repas, c'est légitime.",
        "Une pause de dix minutes et tu finiras bien mieux.",
        "Le jour baisse dehors et ta tasse est vide.",
        "Range ton bureau, tu retrouveras tout plus vite demain.",
        "Prépare ta liste de demain avant d'oublier la moitié.",
        "Un goûter, ça n'a pas d'âge, on est d'accord.",
        "Ton cerveau tourne au ralenti, un sucre le relancera.",
        "Tu peux tenir sans grignoter, mais pourquoi te compliquer la vie.",
        "Le dernier commit de la journée est souvent le plus bâclé.",
        "Encore deux tâches et tu auras le droit de souffler.",
        "Ta tasse froide traîne là depuis un très long moment.",
        "Fin de journée en vue, ne cours pas après un miracle.",
    ]

    static let heureSoiree: [String] = [
        "La journée de travail est finie, la tienne commence vraiment.",
        "Ferme les onglets du boulot, ils tiendront jusqu'à demain.",
        "C'est le moment des projets qu'on fait par plaisir.",
        "Dîner d'abord, terminal ensuite, ça marche mieux dans ce sens.",
        "Le calme du soir vaut bien mieux que celui du matin.",
        "Tu souffles enfin, ça s'entend jusqu'ici.",
        "Le code vraiment amusant, c'est celui du soir.",
        "Les casseroles avant les commits, juste pour cette fois.",
        "Personne ne t'écrira pour le travail maintenant, savoure.",
        "Ton projet perso attend depuis trois jours, il boude un peu.",
        "Une soirée entière devant toi, ne la donne pas au boulot.",
        "Le micro-ondes ou une vraie casserole, à toi de voir.",
        "Ta journée est finie, arrête de relire ce message.",
        "Les meilleures idées arrivent après le dîner, curieusement.",
        "Mets de la musique, le terminal est plus sympa avec.",
        "Tu as le droit de ne rien produire ce soir.",
        "Ce chapitre à réviser peut aussi attendre demain, honnêtement.",
        "Le soir, ton code te ressemble beaucoup plus.",
        "Tu as fermé le laptop du travail, je note le progrès.",
        "Une série, un plat chaud, zéro notification, programme parfait.",
        "Ce bug du bureau n'est plus ton problème ce soir.",
        "La soirée est jeune et ton ventilo est enfin silencieux.",
        "Cuisine quelque chose, ça sentira mieux que le café froid.",
        "Le meilleur moment de la journée commence, ne le rate pas.",
        "Range la vaisselle du midi, tu te sentiras étrangement mieux.",
    ]

    static let heureFatigue: [String] = [
        "Ton bâillement était impressionnant, je l'ai vu d'ici.",
        "L'écran dans le noir, c'est joli mais tes yeux détestent.",
        "Un dernier commit et on éteint, dis-moi que c'est vrai.",
        "Tu relis la même phrase depuis deux bonnes minutes.",
        "La lumière de la pièce a disparu sans que tu remarques.",
        "Il est encore raisonnable d'arrêter, dans une heure moins.",
        "Ton café du soir ne trompera personne, surtout pas moi.",
        "Tes fautes de frappe se multiplient, c'est un bon indicateur.",
        "Ce problème sera plus simple demain, il l'est toujours.",
        "Ferme le terminal pendant que c'est encore ton idée.",
        "Baisse la luminosité, tes yeux te remercieront ce soir.",
        "Une douche chaude puis dodo, très bonne suite de commandes.",
        "Tu as les yeux qui piquent depuis un moment déjà.",
        "Le lit est plus proche que la solution de ce bug.",
        "Encore un chapitre et tu t'endors sur le clavier.",
        "Range ton travail maintenant, tu redémarreras plus vite demain.",
        "Ta concentration est partie se coucher bien avant toi.",
        "Une dernière page, on connaît la fin de cette histoire.",
        "Le silence de la maison te dit quelque chose, écoute-le.",
        "Tes épaules sont raides et ta nuque aussi, je parie.",
        "Note ton idée quelque part et va dormir dessus.",
        "Tu as fait assez pour aujourd'hui, vraiment.",
        "Le ventilo s'est enfin calmé, imite-le un peu.",
        "Ton lit est fait, ça serait dommage de gâcher ça.",
        "Demain matin, ce code aura l'air beaucoup plus clair.",
    ]
}
