import Foundation

/// Répliques de vie hors interaction : retour après absence, ennui, fatigue.
extension ScriptedLines {
    static func welcomeBack(duree: String) -> [String] { [
        "Tiens, \(duree) d'absence et pas un mot, bravo.",
        "\(duree) pile, oui j'ai compté, évidemment.",
        "Te revoilà après \(duree), l'écran commençait à déprimer.",
        "\(duree) sans toi, même le ventilo s'est tu.",
        "Alors, \(duree) pour un café, sérieusement ?",
        "J'ai gardé ta session ouverte pendant \(duree), de rien.",
        "\(duree) d'absence, j'ai failli lancer un scan sans toi.",
        "De retour après \(duree), moi je prenais la poussière.",
        "Pas de panique, en \(duree) rien n'a explosé.",
        "Pendant \(duree), ton terminal et moi on s'est ennuyés poliment.",
        "Tu disparais \(duree) et tu reviens comme si de rien.",
        "J'ai chronométré, \(duree), c'est pour la science.",
        "\(duree) toute seule avec tes onglets, j'ai mérité une caresse.",
        "Reviens plus vite, \(duree) c'est long ici.",
        "\(duree) d'absence, tes notifications ont fait la fête sans toi.",
        "Tu ne m'as pas manqué du tout pendant \(duree), promis.",
        "\(duree), et moi je surveillais le curseur clignoter.",
        "Enfin, ça fait \(duree) que je fixe ce fond d'écran.",
        "\(duree) dehors, j'espère que le café en valait la peine.",
        "L'écran a dormi \(duree), pas moi.",
        "\(duree) sans commit, ton dépôt s'inquiétait un peu.",
        "Note pour plus tard, \(duree), record personnel d'abandon.",
        "Te revoilà, je remets le ventilo en route.",
        "Ah, enfin du mouvement devant l'écran.",
        "Je n'ai pas bougé d'un pixel, c'est ma grande fierté.",
        "Reprends ta place, j'ai tenu le fort.",
        "Tiens, une revenante, je préviens le terminal.",
        "Tu tombes bien, il ne se passait strictement rien.",
        "Assieds-toi, je te raconte, il ne s'est rien passé.",
        "J'allais lancer un avis de recherche.",
    ] }

    static func bored() -> [String] { [
        "Rien depuis une heure, même le curseur s'endort.",
        "On lance un scan sur quelque chose, n'importe quoi ?",
        "Je m'ennuie tellement que je lis tes logs.",
        "Propose un défi, même un ping me suffira.",
        "Ouvre un terminal, juste pour voir du texte défiler.",
        "Le disque dur ronronne plus que moi, vexant.",
        "Écris un script inutile, je le regarderai tourner.",
        "Il ne se passe rien, j'ai vérifié deux fois.",
        "Même ta corbeille est vide, c'est dire.",
        "Un petit scan du grille-pain connecté, ça te tente ?",
        "Je compte les pixels, j'en suis à beaucoup.",
        "Ton fond d'écran et moi, on se connaît par cœur.",
        "Fais défiler quelque chose, mes yeux rouillent.",
        "Une notification, une seule, je ne demande pas grand-chose.",
        "On pourrait renommer tous tes fichiers, pour rire.",
        "Le ventilo s'est arrêté, c'est le silence total.",
        "Compile un truc énorme, j'adore regarder les barres.",
        "Je m'entraîne à fixer le vide, niveau expert.",
        "Ta RAM dort à moitié, réveille-la un peu.",
        "Lance un htop, on regardera bouger les chiffres ensemble.",
        "Il paraît qu'ailleurs il se passe des choses.",
        "J'ai relu ton historique de commandes, deux fois.",
        "Un capture the flag, là, tout de suite ?",
        "Même les mises à jour se font discrètes aujourd'hui.",
        "Casse quelque chose, qu'on ait enfin du débogage.",
        "Je pourrais trier tes téléchargements par ordre d'oubli.",
        "Ton clavier refroidit, c'est mauvais signe.",
        "Zéro commit aujourd'hui, le dépôt fait la sieste.",
        "On audite le wifi de la maison, pour voir ?",
        "Je m'ennuie assez pour lire une doc en entier.",
        "Bouge la souris, fais-moi croire à de l'action.",
        "L'écran de veille menace d'arriver, sauve-nous.",
        "Encore cinq minutes de calme et je défragmente le disque.",
        "Dis un mot dans le terminal, je ferai écho.",
        "Le silence radio, très peu pour moi.",
        "On monte un serveur pour rien, juste le plaisir ?",
        "Tes onglets ouverts s'ennuient autant que moi.",
        "Un grep au hasard, on verra ce qui sort.",
        "Je répète mes cabrioles devant un public de dossiers.",
        "Programme-moi une distraction, tu sais coder pourtant.",
    ] }

    static func tired() -> [String] { [
        "Il est tard, même le ventilo bâille.",
        "Mes pixels commencent à cligner tout seuls.",
        "Encore un onglet et après on dort, promis ?",
        "Je vais passer en veille avant ta machine, là.",
        "L'heure au coin de l'écran devient absurde.",
        "Ton café ne fait même plus semblant de marcher.",
        "Je bâille en binaire, c'est mauvais signe.",
        "On sauvegarde tout et on file au lit ?",
        "Même les serveurs redémarrent la nuit, eux.",
        "Mes paupières pèsent un disque dur chacune.",
        "Le dernier commit peut attendre demain, il est sage.",
        "Je somnole, préviens-moi si tu fermes tout.",
        "L'écran chauffe moins que tes yeux, je parie.",
        "Passé cette heure, les bugs gagnent toujours.",
        "Un dodo maintenant, un cerveau frais demain, bonne affaire.",
        "Je tiens debout par habitude, plus par énergie.",
        "La veille nocturne, très surfait comme mode de vie.",
        "Éteins l'écran, je garderai le bureau au chaud.",
        "Ferme le terminal en douceur, il dort déjà à moitié.",
        "Mes animations tournent au ralenti, regarde.",
        "Il est tard au point que les logs datent d'hier.",
        "Je compte les moutons dans ta barre des tâches.",
        "Encore éveillées toutes les deux, quel duo déraisonnable.",
        "Demain le code sera encore là, lui.",
        "Je pique du nez sur ton dock.",
        "L'horloge a dépassé l'heure des bonnes idées.",
        "Ton ventilo souffle plus fort que ma motivation.",
        "Enregistre, éteins, dors, dans cet ordre précis.",
        "Je rêve déjà à moitié de barres de progression.",
        "Va dormir, je surveille les notifications pour toi.",
    ] }
}
