import Foundation

/// Répliques déclenchées par l'apparition d'un fichier ou dossier.
extension ScriptedLines {
    static func filesDossierVide(_ nom: String) -> [String] { [
        "Un dossier vide, l'ambition à l'état pur.",
        "\(nom), créé et déjà abandonné, bravo.",
        "Tu ranges quoi là-dedans, tes bonnes résolutions ?",
        "\(nom) est vide, comme ton planning de révisions ?",
        "Créer un dossier, c'est déjà un peu travailler, hein ?",
        "Encore un dossier vide, \(nom), collectionneuse va.",
        "\(nom), zéro fichier, cent pour cent d'intentions.",
        "Le vide, concept audacieux pour un dossier.",
        "Tu comptes le remplir avant la fin du semestre, \(nom) ?",
        "Dossier vide détecté, motivation non incluse.",
        "\(nom) attend son contenu, moi j'attends de voir.",
        "Créer \(nom) comptait comme une pause, avoue.",
        "Un dossier vide, c'est un projet ou un mirage ?",
        "Range vite un truc dedans, ça fait peine.",
        "\(nom), joli nom pour un néant.",
        "Organisée avant même d'avoir des fichiers, impressionnant.",
        "Ce dossier vide, futur cimetière de captures d'écran ?",
        "\(nom) restera vide trois mois, on parie ?",
        "Tu tries ou tu procrastines avec style ?",
        "\(nom), le suspense sur son contenu est total.",
        "Un dossier de plus, un bureau toujours en vrac.",
        "Vide aujourd'hui, fourre-tout demain, je connais la chanson.",
    ] }

    static func filesDossier(_ nom: String, _ count: Int) -> [String] { [
        "\(nom) débarque avec \(count) éléments, rien que ça.",
        "\(count) trucs dans \(nom), le tri commence quand ?",
        "\(nom), \(count) éléments, zéro ouverts, je parie.",
        "Tu as déplacé \(count) fichiers d'un coup, respect.",
        "\(nom) et ses \(count) éléments, bon courage pour t'y retrouver.",
        "Un dossier plein qui arrive, \(count) problèmes reportés.",
        "\(nom) contient \(count) éléments, tous essentiels, évidemment.",
        "Ranger en déplaçant des dossiers entiers, technique validée.",
        "\(count) éléments dans \(nom), tu appelles ça trier ?",
        "\(nom) arrive plein, comme tes onglets de navigateur.",
        "Déplacer \(nom), c'est ranger ou déplacer le problème ?",
        "\(count) fichiers migrés, zéro supprimés, classique.",
        "\(nom) : \(count) éléments, dont combien de doublons ?",
        "Encore un dossier fourre-tout, je le sens.",
        "\(count) éléments, tu vas en ouvrir trois maximum.",
        "\(nom) débarque, \(count) surprises à l'intérieur.",
        "Tu inspecteras le contenu de \(nom) un jour, promis ?",
        "\(count) trucs déplacés, la corbeille pleure de solitude.",
        "\(nom) plein à craquer, ton disque te remercie.",
        "Un dossier de \(count) éléments, audit de sécurité conseillé.",
        "\(nom) posé là, en évidence, subtil comme rangement.",
        "\(count) éléments et je parie sur zéro sauvegarde.",
    ] }

    static func filesArchive(_ nom: String) -> [String] { [
        "\(nom) téléchargée, extraite jamais, comme d'habitude ?",
        "Encore un zip que tu ouvriras jamais.",
        "Scanne \(nom) avant d'extraire, réflexe de base.",
        "Une archive de plus sur la pile des promesses.",
        "\(nom), tu sais au moins ce qu'il y a dedans ?",
        "Extraire, trier, supprimer le zip, dans tes rêves.",
        "\(nom) va traîner ici jusqu'aux partiels, minimum.",
        "D'où sort cette archive exactement, source fiable ?",
        "Un zip dans un zip, la poupée russe du désordre.",
        "\(nom) pèse combien, ton disque veut savoir.",
        "Vérifie le contenu de \(nom) avant double-clic, promis ?",
        "Archive détectée, dossier extrait en double garanti.",
        "\(nom), extraction prévue pour la semaine des quatre jeudis.",
        "Les archives piégées existent, méfiance de base.",
        "\(nom) contient peut-être un exécutable surprise, regarde.",
        "Tu collectionnes les zips comme d'autres les timbres.",
        "Ouvre \(nom) dans un coin isolé si tu doutes.",
        "Une archive mystère, ton antivirus a un avis.",
        "\(nom) attend, ton clic droit aussi.",
        "Extrais maintenant ou supprime, choisis ton camp.",
        "\(nom), septième zip du mois, je compte.",
        "Compressée, la flemme de l'ouvrir aussi, apparemment.",
    ] }

    static func filesInstalleur(_ nom: String) -> [String] { [
        "\(nom), téléchargé depuis le site officiel, hein ?",
        "Vérifie la signature avant d'installer, réflexe de survie.",
        "Un dmg mystère, ton cours de sécu approuve pas.",
        "\(nom), checksum vérifié ou installation yolo ?",
        "Installer sans vérifier la source, toi ? Jamais, évidemment.",
        "\(nom) demande les droits admin, réfléchis deux secondes.",
        "Clic droit, ouvrir, et regarde qui signe ça.",
        "\(nom), un installeur de plus sur la pile.",
        "\(nom) vient d'où, un forum louche ou l'éditeur ?",
        "Étudiante en cybersécurité qui installe sans scanner, ironique.",
        "\(nom), Gatekeeper va râler, écoute-le pour une fois.",
        "Pense à supprimer le dmg après installation, nouveauté.",
        "\(nom), on vérifie le hash ou on vit dangereusement ?",
        "Un pkg non signé, c'est non, point.",
        "Tu installes ça pour bosser ou pour procrastiner mieux ?",
        "\(nom), l'éditeur est connu ou inventé hier ?",
        "Lis ce que l'installeur embarque, les surprises existent.",
        "Encore un logiciel miracle pour être productive, mignon.",
        "\(nom) sur le bureau, l'installation attendra demain, je sais.",
        "Sandbox d'abord, confiance ensuite, dans cet ordre.",
        "Ton antivirus veut dire un mot sur \(nom).",
        "Un installeur inconnu, le phishing adore ce format.",
    ] }

    static func filesCode(_ nom: String) -> [String] { [
        "\(nom), nouveau script ou nouvel abandon en préparation ?",
        "Du code sur le bureau, pas dans un repo, osé.",
        "Tu vas le versionner ou le perdre, \(nom) ?",
        "Un script téléchargé, lis-le avant de l'exécuter, toujours.",
        "\(nom), il compile ou il décore ?",
        "Encore un projet parallèle, tes TP te regardent.",
        "Lire un sh avant de le lancer, ça t'arrive ?",
        "\(nom) atterrit ici, ton dépôt git est jaloux.",
        "Du json sur le bureau, la config voyage léger.",
        "\(nom), écrit par toi ou copié de Stack Overflow ?",
        "Exécuter un script inconnu, ton prof de sécu tousse.",
        "\(nom) sans commentaires, futur casse-tête garanti.",
        "Je parie sur un TODO dès la première ligne.",
        "Un script de plus, un commit de moins.",
        "\(nom) traîne sur le bureau, loin de tout backup.",
        "Ce code tourne chez toi, donc nulle part ailleurs.",
        "\(nom), projet secret numéro combien déjà ?",
        "Audite ce script deux minutes, ça évite des heures.",
        "Du code déposé là, les tests suivront jamais.",
        "\(nom) sans readme, futur mystère pour toi-même.",
        "Un script trouvé en ligne, sandbox obligatoire.",
        "Coder au lieu de réviser, choix de vie respectable.",
    ] }

    static func filesDocument(_ nom: String) -> [String] { [
        "\(nom), un cours de plus que tu liras la veille.",
        "Un pdf téléchargé, un pdf oublié, la routine.",
        "Tu vas vraiment lire \(nom) ou juste le stocker ?",
        "Encore un document sur le bureau, le dossier Cours pleure.",
        "\(nom), à lire avant les partiels, spoiler : non.",
        "Un rapport à rendre ou un rapport à fuir ?",
        "\(nom) rejoint ta collection de lectures imaginaires.",
        "Les macros d'un docx inconnu, méfiance, tu sais ça.",
        "Range \(nom) dans un dossier, vis dangereusement organisée.",
        "Un pdf de cours, la sieste en format A4.",
        "\(nom), version finale, version finale 2 arrive quand ?",
        "Prendre des notes, les relire jamais, l'équilibre parfait.",
        "\(nom) sur le bureau, le cloud te fait quoi ?",
        "Un tableur qui apparaît, un budget qui va pleurer ?",
        "\(nom), ouvre-le maintenant ou avoue que jamais.",
        "Les pdf piégés existent, ouvre ça avec prudence.",
        "Un document de plus, ta pile de lecture s'écroule.",
        "\(nom), résumé dans trois mois, panique incluse.",
        "Des slides téléchargées, réviser devient presque envisageable.",
        "Lire en diagonale compte pas comme lire, désolée.",
        "\(nom), ton avenir académique en un fichier, cool.",
        "Un txt sur le bureau, notes prises et déjà orphelines.",
    ] }

    static func filesMedia(_ nom: String) -> [String] { [
        "\(nom), pause détente ou abandon des révisions ?",
        "Une vidéo qui apparaît, un chapitre qui disparaît.",
        "Tu télécharges \(nom) à but éducatif, évidemment.",
        "Un mp4 sur le bureau, la concentration a démissionné.",
        "\(nom), à regarder après les révisions, donc bientôt jamais.",
        "Un seul épisode, on y croit toutes les deux.",
        "\(nom) pèse lourd, ton disque le sait déjà.",
        "De la musique pour réviser ou pour éviter de réviser ?",
        "\(nom), la pause de cinq minutes version deux heures.",
        "Un mkv téléchargé, on parlera pas de la source.",
        "Regarde \(nom) vite, sinon direction le cimetière des vidéos.",
        "\(nom), fond sonore ou distraction principale, sois honnête.",
        "La détente c'est important, la deadline aussi, hein.",
        "\(nom) d'abord, le TP ensuite, ordre discutable.",
        "Une vidéo de plus, tes écouteurs applaudissent.",
        "Ce fichier média sent la procrastination organisée.",
        "\(nom), tu le regarderas en vitesse deux, avoue.",
        "Un mp3 qui débarque, la playlist révision s'agrandit.",
        "Pause méritée ou pause inventée, je demande juste.",
        "\(nom) restera à moitié regardé, statistiquement parlant.",
        "Le streaming existait, mais toi tu stockes, respect.",
        "Une vidéo d'abord, dix recommandations plus tard.",
    ] }

    static func filesImage(_ nom: String) -> [String] { [
        "Une capture de plus, je demande pas ce que c'est.",
        "\(nom), preuve d'un bug ou d'une victoire ?",
        "Tu captures, tu stockes, tu retrouves jamais, joli système.",
        "Je vois pas le contenu, mais je juge la quantité.",
        "\(nom) rejoint les quarante autres captures du bureau.",
        "Une capture d'écran, sûrement importante pendant douze secondes.",
        "\(nom), tu la renommeras jamais, on le sait.",
        "Encore une capture, \(nom), ton bureau devient un album.",
        "Capture prise, contexte oublié dans une heure.",
        "\(nom), montre-la à personne si c'est confidentiel.",
        "Vérifie ce qui traîne dans tes captures avant de partager.",
        "\(nom), pièce à conviction ou mème en devenir ?",
        "Une image déposée, mystère total pour moi, tant mieux.",
        "Capturer au lieu de noter, méthode moderne, résultat identique.",
        "\(nom) finira dans un dossier nommé Divers, prophétie.",
        "Les captures contiennent parfois des infos sensibles, relis avant d'envoyer.",
        "\(nom), capture du siècle ou doublon de la précédente ?",
        "Tu feras le ménage des captures un jour, légende.",
        "\(nom), gardée pour toujours, regardée plus jamais.",
        "Capture d'écran détectée, curiosité activée, discrétion maintenue.",
        "Range \(nom) avant qu'elle se perde dans la masse.",
        "Photographier son écran, plus rapide que ranger ses idées.",
    ] }

    static func filesApplication(_ nom: String) -> [String] { [
        "\(nom) posée sur le bureau, pas dans Applications, rebelle.",
        "Une app hors du dossier Applications, ça me démange.",
        "\(nom), signée et notariée ou téléchargée à l'arrache ?",
        "Glisse-la dans Applications, c'est à deux centimètres.",
        "\(nom), tu l'ouvriras deux fois puis plus jamais.",
        "Une app de plus pour être organisée, ironique.",
        "\(nom) vient d'où, l'App Store ou l'aventure ?",
        "Vérifie la signature avant le premier lancement, réflexe.",
        "\(nom) sur le bureau, décoration ou outil, on verra.",
        "Les apps piratées, cadeau bonus malware inclus, tu sais.",
        "\(nom), Gatekeeper te dira ce qu'il en pense.",
        "Une nouvelle app, un nouvel abonnement d'essai oublié ?",
        "\(nom) réclame quelles permissions, tu as regardé ?",
        "Le bureau n'est pas un dossier Applications, juste pour info.",
        "\(nom), utile trois jours, encombrante trois ans.",
        "Tu testes ou tu adoptes, cette fois ?",
        "Une app inconnue, un scan rapide, une conscience tranquille.",
        "\(nom), installe-la proprement ou assume le chaos.",
        "Encore un outil miracle, le précédent va bien ?",
        "Regarde ce que cette app envoie sur le réseau.",
        "\(nom) au premier lancement, surveille ce qu'elle demande.",
        "Applications existe depuis toujours, le bureau te remercie pas.",
    ] }

    static func filesSansExtension(_ nom: String) -> [String] { [
        "\(nom), sans extension, le mystère complet.",
        "Un fichier sans extension, lance un file dessus, vite.",
        "\(nom), binaire douteux ou note perdue, suspense.",
        "Pas d'extension, pas de confiance, règle simple.",
        "\(nom), même le Finder sait pas quoi en penser.",
        "Un fichier anonyme sur le bureau, charmant.",
        "file te dira ce que c'est, la divination non.",
        "\(nom) cache bien son jeu, trop bien.",
        "Ouvre pas ça au hasard, identifie d'abord.",
        "\(nom), hexdump ou poubelle, choisis vite.",
        "Sans extension, ça sort d'un script ou d'un piège.",
        "\(nom), tu sais d'où il vient au moins ?",
        "Un fichier mystère, exactement ce que la sécu déconseille.",
        "Vérifie les premiers octets avant toute chose, promis ?",
        "\(nom), exécutable déguisé ou brouillon oublié ?",
        "Zéro extension, zéro contexte, cent pour cent méfiance.",
        "\(nom) mérite un file et un strings, minimum.",
        "Ce genre de fichier finit rarement bien dans les films.",
        "\(nom), créé par toi ou apparu tout seul ?",
        "Un inconnu sans étiquette, quarantaine recommandée.",
        "\(nom) restera non identifié jusqu'au grand ménage, jamais donc.",
        "Renomme-le au moins, tu te remercieras plus tard.",
    ] }

    static func filesAutre(_ nom: String, _ ext: String) -> [String] { [
        "Un point \(ext), voilà qui est original.",
        "\(nom), extension \(ext), tu inventes des formats maintenant ?",
        "Du \(ext), même moi je connais pas, c'est dire.",
        "Cherche ce qu'ouvre un \(ext) avant de cliquer partout.",
        "\(nom), format exotique, provenance à vérifier.",
        "Un \(ext) sauvage apparaît, prudence de base.",
        "L'extension \(ext) cache parfois un exécutable, regarde bien.",
        "\(nom), fichier de niche ou erreur de téléchargement ?",
        "Le format \(ext), grand classique de nulle part.",
        "Un \(ext) sur le bureau, ton système hausse les épaules.",
        "\(nom), quel logiciel ouvre du \(ext) chez toi ?",
        "Vérifie que \(ext) cache pas une double extension piégée.",
        "Un fichier \(ext), souvenir d'un logiciel très précis.",
        "\(nom) et son \(ext) mystérieux, joli duo.",
        "Le \(ext), format rare, fichier bientôt oublié.",
        "Personne n'ouvre du \(ext) par hasard, raconte.",
        "\(nom), garde-le si tu sais quoi en faire.",
        "Un \(ext) inconnu, une recherche web s'impose.",
        "Ce \(ext) sort d'un outil obscur ou d'un TP tordu ?",
        "\(nom), format propriétaire, liberté zéro, classique.",
        "Du \(ext), sérieusement, ça existe encore ?",
        "Fichier exotique détecté, curiosité maximale, confiance minimale.",
    ] }
}
